Repository hmathieu-insat/PIR, pull requests merged in 2022-05, with the labels that each got.

#44 40 finish configuration of usart
  Nouveau PIR/firmware/source/main.c
  Nouveau PIR/firmware/source/uart.c
Labels: enhancement

#71 Implement failures.c
  Nouveau PIR/firmware/header/Tim5.h
  Nouveau PIR/firmware/header/timer.h
  Nouveau PIR/firmware/source/Tim5.c
  Nouveau PIR/firmware/source/failures.c
  Nouveau PIR/firmware/source/main.c
  Nouveau PIR/firmware/source/timer.c
Labels: Major

#95 ➖ Remove inexistent config.h import
  Nouveau PIR/firmware/source/failures.c
  Nouveau PIR/firmware/source/main.c
Labels: bug

#120 Renamed uart to usart everywhere
  Nouveau PIR/firmware/header/usart.h
  Nouveau PIR/firmware/source/main.c
  Nouveau PIR/firmware/source/port_config.c
  Nouveau PIR/firmware/source/synchronization.c
  Nouveau PIR/firmware/source/system_configuration.c
  Nouveau PIR/firmware/source/usart.c
Labels: documentation
