Repository hmathieu-insat/PIR, pull requests merged in 2022-03, with the labels that each got.

#1 Interface web
  Nouveau PIR/docs/.DS_Store
  Nouveau PIR/docs/continental/JammerBox_presentation.pdf
  Nouveau PIR/docs/continental/UART_ProtocolOverview.xlsx
  Nouveau PIR/docs/continental/UserGuide.pdf
  Nouveau PIR/firmware/ENSD_Jammer.X/Makefile
  Nouveau PIR/firmware/ENSD_Jammer.X/nbproject/configurations.xml
  Nouveau PIR/firmware/ENSD_Jammer.X/nbproject/project.xml
  Nouveau PIR/firmware/header/config.h
  Nouveau PIR/firmware/header/failures.h
  Nouveau PIR/firmware/header/ic.h
  Nouveau PIR/firmware/header/osc.h
  Nouveau PIR/firmware/header/port_config.h
  Nouveau PIR/firmware/header/synchronization.h
  Nouveau PIR/firmware/header/system_configuration.h
  Nouveau PIR/firmware/header/timer.h
  Nouveau PIR/firmware/header/uart.h
  Nouveau PIR/firmware/source/failures.c
  Nouveau PIR/firmware/source/ic.c
  Nouveau PIR/firmware/source/main.c
  Nouveau PIR/firmware/source/osc.c
  Nouveau PIR/firmware/source/port_config.c
  Nouveau PIR/firmware/source/synchronization.c
  Nouveau PIR/firmware/source/system_configuration.c
  Nouveau PIR/firmware/source/timer.c
  Nouveau PIR/firmware/source/uart.c
  Nouveau PIR/interface-web/.gitignore
  Nouveau PIR/interface-web/README.md
  Nouveau PIR/interface-web/package-lock.json
  Nouveau PIR/interface-web/package.json
  Nouveau PIR/interface-web/public/favicon.ico
  Nouveau PIR/interface-web/public/index.html
  Nouveau PIR/interface-web/public/logo192.png
  Nouveau PIR/interface-web/public/logo512.png
  Nouveau PIR/interface-web/public/manifest.json
  Nouveau PIR/interface-web/public/robots.txt
  Nouveau PIR/interface-web/src/App.css
  Nouveau PIR/interface-web/src/App.js
  Nouveau PIR/interface-web/src/App.test.js
  Nouveau PIR/interface-web/src/index.css
  Nouveau PIR/interface-web/src/index.js
  Nouveau PIR/interface-web/src/logo.svg
  Nouveau PIR/interface-web/src/reportWebVitals.js
  Nouveau PIR/interface-web/src/setupTests.js
  Nouveau PIR/interface-web/yarn.lock
Labels: good first issue

#16 🔨 Update Makefile to compile tests
  Nouveau PIR/firmware/ENSD_Jammer.X/Makefile
Labels: bug

#17 11-✨Port-Output_CRK_no_failure
  .gitignore
  Nouveau PIR/firmware/header/port_config.h
  Nouveau PIR/firmware/source/failures.c
  Nouveau PIR/firmware/source/main.c
  Nouveau PIR/firmware/source/port_config.c
  Nouveau PIR/firmware/test/test_GPIO.c
Labels: enhancement
